version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - .:/rails
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql2://root:password@db:3306
      RAILS_ENV: development

  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
